export const orderListData = [
    {
        
        "applicationId": "YH202505230922293374",
        "orderId": null,
        "applyDate": 1747991317000,
        "taskCode": [
            "checkPartnerQualifications",
            "logisticsCheckCar",
            "preAssessCarPrice"
        ],
        "taskCodeDesc": [
            "运营初审",
            "物流验车",
            "预核价"
        ],
        "orderStatusDesc": "未推送",
        "applicationStatus": 5,
        "applicationStatusDesc": "审核中",
        "regionId": null,
        "areaName": null,
        "dealName": "汽车有限公司",
        "providerId": 100011125,
        "providerName": "上海科技有限公司",
        "providerUserId": 100028666,
        "providerUserName": "张三",
        "providerUserPhone": "13048575748",
        "isMakeOrder": true,
        "isSurvey": "尽调已过期",
        "contractAmount": 60000000,
        "contractAmountCNY": "600,000",
        "loanAmount": null,
        "loanAmountCNY": null,
        "managerId": null,
        "manager": null,
        "managerNick": null,
        "userName": "张三",
        "userMobile": "15839886688",
        "contactsName": "李四",
        "contactsPhone": "17816860000",
        "storeId": null,
        "wareHouseDetail": null,
        "transportInfo": null,
        "totalCar": 2,
        "carDetail": [
            {
                "modelName": "奥迪A7L 2024款 45 TFSI quattro 黑武士版",
                "uniqueNum": 2,
                "carUniqueList": []
            }
        ],
        "productType": 27,
        "productTypeDesc": "订单宝-银行精选",
        "dealerId": 100011120,
        "userId": 100028660,
        "signerName": "张三",
        "signerMobile": "15839886688",
        "lowerReaches": null,
        "lowerReachesId": null,
        "upperReaches": null,
        "upperReachesId": null,
        "labelInfo": null,
        "orderSourceNum": null,
        "createInvoice": null,
        "isExtension": null,
        "extensionBatchNo": null,
        "applyLoanAmount": 60000000,
        "applyLoanAmountCNY": "600,000",
        "totalCheckAmount": null,
        "matAmount": null,
        "isModifyInfo": true,
        "memo": null,
        "closeSource": null,
        "source": 0,
        "canTestClose": false,
        "isShowBankButton": true,
        "isDoBankButton": true,
        "isExportButton": false,
        "receiptInfoDTOS": [
            {
                "receiptAmount": 60000000,
                "receiptMemo": "",
                "isPrivatePayment": 0,
                "accountId": 1254,
                "accountName": "上海科技有限公司",
                "bankCardNo": "123456789",
                "bankId": 8,
                "bankName": "招商银行",
                "province": "浙江省",
                "city": "杭州市",
                "bankBranch": "招商银行杭州分行城西支行",
                "bankReceiptUrl": null,
                "type": null,
                "advanceTime": null,
                "remark": null
            }
        ],
        "orderFollowerId": null,
        "orderFollowerName": null
    },
    {
        "applicationId": "YH202505230919583236",
        "orderId": null,
        "applyDate": 1747967828000,
        "taskCode": [
            "checkPartnerQualifications",
            "logisticsCheckCar",
            "preAssessCarPrice"
        ],
        "taskCodeDesc": [
            "运营初审",
            "物流验车",
            "预核价"
        ],
        "orderStatusDesc": "未推送",
        "applicationStatus": 5,
        "applicationStatusDesc": "审核中",
        "regionId": null,
        "areaName": null,
        "dealName": "汽车有限公司",
        "providerId": 100011125,
        "providerName": "上海科技有限公司",
        "providerUserId": 100028666,
        "providerUserName": "张三",
        "providerUserPhone": "15839886688",
        "isMakeOrder": true,
        "isSurvey": "尽调已过期",
        "contractAmount": 7000000,
        "contractAmountCNY": "70,000",
        "loanAmount": null,
        "loanAmountCNY": null,
        "managerId": null,
        "manager": null,
        "managerNick": null,
        "userName": "张三",
        "userMobile": "15839886688",
        "contactsName": "李四",
        "contactsPhone": "17816860000",
        "storeId": null,
        "wareHouseDetail": null,
        "transportInfo": null,
        "totalCar": 1,
        "carDetail": [
            {
                "modelName": "奥迪A7L 2024款 45 TFSI 豪华型",
                "uniqueNum": 1,
                "carUniqueList": []
            }
        ],
        "productType": 27,
        "productTypeDesc": "订单宝-银行精选",
        "dealerId": 100011120,
        "userId": 100028660,
        "signerName": "张三",
        "signerMobile": "15839886688",
        "lowerReaches": null,
        "lowerReachesId": null,
        "upperReaches": null,
        "upperReachesId": null,
        "labelInfo": null,
        "orderSourceNum": null,
        "createInvoice": null,
        "isExtension": null,
        "extensionBatchNo": null,
        "applyLoanAmount": 7000000,
        "applyLoanAmountCNY": "70,000",
        "totalCheckAmount": null,
        "matAmount": null,
        "isModifyInfo": true,
        "memo": null,
        "closeSource": null,
        "source": 0,
        "canTestClose": false,
        "isShowBankButton": true,
        "isDoBankButton": true,
        "isExportButton": false,
        "receiptInfoDTOS": [
            {
                "receiptAmount": 7000000,
                "receiptMemo": "",
                "isPrivatePayment": 0,
                "accountId": 1254,
                "accountName": "上海科技有限公司",
                "bankCardNo": "123456789",
                "bankId": 8,
                "bankName": "招商银行",
                "province": "浙江省",
                "city": "杭州市",
                "bankBranch": "招商银行杭州分行城西支行",
                "bankReceiptUrl": null,
                "type": null,
                "advanceTime": null,
                "remark": null
            }
        ],
        "orderFollowerId": null,
        "orderFollowerName": null
    },
    {
        "applicationId": "YH202505220916333584",
        "orderId": null,
        "applyDate": 1747897777000,
        "taskCode": [
            "checkPartnerQualifications",
            "logisticsCheckCar",
            "preAssessCarPrice"
        ],
        "taskCodeDesc": [
            "运营初审",
            "物流验车",
            "预核价"
        ],
        "orderStatusDesc": "未推送",
        "applicationStatus": 5,
        "applicationStatusDesc": "审核中",
        "regionId": null,
        "areaName": null,
        "dealName": "山东信息科技有限公司",
        "providerId": 100011120,
        "providerName": "汽车有限公司",
        "providerUserId": 100028660,
        "providerUserName": "张三",
        "providerUserPhone": "15839886688",
        "isMakeOrder": true,
        "isSurvey": "已通过尽调",
        "contractAmount": 32580000,
        "contractAmountCNY": "325,800",
        "loanAmount": null,
        "loanAmountCNY": null,
        "managerId": null,
        "manager": null,
        "managerNick": null,
        "userName": "张三",
        "userMobile": "15839886688",
        "contactsName": "张三",
        "contactsPhone": "15839886688",
        "storeId": null,
        "wareHouseDetail": null,
        "transportInfo": null,
        "totalCar": 1,
        "carDetail": [
            {
                "modelName": "奥迪A4L 2024款 40 TFSI 时尚动感型",
                "uniqueNum": 1,
                "carUniqueList": []
            }
        ],
        "productType": 27,
        "productTypeDesc": "订单宝-银行精选",
        "dealerId": 100019009,
        "userId": 100071950,
        "signerName": "张三",
        "signerMobile": "15839886688",
        "lowerReaches": null,
        "lowerReachesId": null,
        "upperReaches": null,
        "upperReachesId": null,
        "labelInfo": null,
        "orderSourceNum": null,
        "createInvoice": null,
        "isExtension": null,
        "extensionBatchNo": null,
        "applyLoanAmount": 32580000,
        "applyLoanAmountCNY": "325,800",
        "totalCheckAmount": null,
        "matAmount": null,
        "isModifyInfo": true,
        "memo": null,
        "closeSource": null,
        "source": 0,
        "canTestClose": false,
        "isShowBankButton": true,
        "isDoBankButton": true,
        "isExportButton": false,
        "receiptInfoDTOS": [
            {
                "receiptAmount": 32580000,
                "receiptMemo": "",
                "isPrivatePayment": 0,
                "accountId": 100000271,
                "accountName": "上海科技有限公司",
                "bankCardNo": "123456789123456",
                "bankId": 8,
                "bankName": "招商银行",
                "province": "浙江省",
                "city": "杭州市",
                "bankBranch": "招商银行股份有限公司杭州海创园小微企业专营支行",
                "bankReceiptUrl": null,
                "type": null,
                "advanceTime": null,
                "remark": null
            }
        ],
        "orderFollowerId": null,
        "orderFollowerName": null
    },
    {
        "applicationId": "YH202411140891065340",
        "orderId": null,
        "applyDate": 1731573460000,
        "taskCode": [
            "checkPartnerQualifications",
            "logisticsCheckCar",
            "preAssessCarPrice"
        ],
        "taskCodeDesc": [
            "运营初审",
            "物流验车",
            "预核价"
        ],
        "orderStatusDesc": "未推送",
        "applicationStatus": 5,
        "applicationStatusDesc": "审核中",
        "regionId": null,
        "areaName": null,
        "dealName": "上海安趣盈科技有限公司",
        "providerId": 100011125,
        "providerName": "上海科技有限公司",
        "providerUserId": 100028666,
        "providerUserName": "张三",
        "providerUserPhone": "15839886688",
        "isMakeOrder": true,
        "isSurvey": "尽调已过期",
        "contractAmount": 12000000,
        "contractAmountCNY": "120,000",
        "loanAmount": null,
        "loanAmountCNY": null,
        "managerId": 471622995839938560,
        "manager": "张三",
        "managerNick": "张三",
        "userName": "张三",
        "userMobile": "17816869350",
        "contactsName": "李四",
        "contactsPhone": "17816860000",
        "storeId": null,
        "wareHouseDetail": null,
        "transportInfo": null,
        "totalCar": 1,
        "carDetail": [
            {
                "modelName": "奥迪A4L 2024款 40 TFSI 时尚动感型",
                "uniqueNum": 1,
                "carUniqueList": [
                    "J4MB7E3FXY0B1C48X"
                ]
            }
        ],
        "productType": 27,
        "productTypeDesc": "订单宝-银行精选",
        "dealerId": 100018947,
        "userId": 100071797,
        "signerName": "张三",
        "signerMobile": "15839886688",
        "lowerReaches": null,
        "lowerReachesId": null,
        "upperReaches": null,
        "upperReachesId": null,
        "labelInfo": null,
        "orderSourceNum": null,
        "createInvoice": null,
        "isExtension": null,
        "extensionBatchNo": null,
        "applyLoanAmount": 12000000,
        "applyLoanAmountCNY": "120,000",
        "totalCheckAmount": null,
        "matAmount": null,
        "isModifyInfo": true,
        "memo": null,
        "closeSource": null,
        "source": 0,
        "canTestClose": false,
        "isShowBankButton": true,
        "isDoBankButton": true,
        "isExportButton": false,
        "receiptInfoDTOS": [
            {
                "receiptAmount": 12000000,
                "receiptMemo": "",
                "isPrivatePayment": 0,
                "accountId": 100000271,
                "accountName": "上海科技有限公司",
                "bankCardNo": "123456789123456",
                "bankId": 8,
                "bankName": "招商银行",
                "province": "浙江省",
                "city": "杭州市",
                "bankBranch": "招商银行股份有限公司杭州海创园小微企业专营支行",
                "bankReceiptUrl": null,
                "type": null,
                "advanceTime": null,
                "remark": null
            }
        ],
        "orderFollowerId": null,
        "orderFollowerName": null
    },
    {
        "applicationId": "YH202411060879036513",
        "orderId": null,
        "applyDate": 1730881462000,
        "taskCode": [
            "checkPartnerQualifications",
            "preAssessCarPrice"
        ],
        "taskCodeDesc": [
            "运营初审",
            "预核价"
        ],
        "orderStatusDesc": "未推送",
        "applicationStatus": 5,
        "applicationStatusDesc": "审核中",
        "regionId": null,
        "areaName": null,
        "dealName": "上海安趣盈科技有限公司",
        "providerId": 100011125,
        "providerName": "上海科技有限公司",
        "providerUserId": 100028666,
        "providerUserName": "张三",
        "providerUserPhone": "15839886688",
        "isMakeOrder": true,
        "isSurvey": "尽调已过期",
        "contractAmount": 17000000,
        "contractAmountCNY": "170,000",
        "loanAmount": null,
        "loanAmountCNY": null,
        "managerId": 471622995839938560,
        "manager": "张三",
        "managerNick": "张三",
        "userName": "张三",
        "userMobile": "17816869350",
        "contactsName": "李四",
        "contactsPhone": "17816860000",
        "storeId": null,
        "wareHouseDetail": null,
        "transportInfo": null,
        "totalCar": 2,
        "carDetail": [
            {
                "modelName": "奥迪A4L 2020款 35 TFSI 时尚动感型",
                "uniqueNum": 1,
                "carUniqueList": []
            },
            {
                "modelName": "宝骏530 2021款 全球车周年纪念版 1.5T 手动舒适型 5座",
                "uniqueNum": 1,
                "carUniqueList": []
            }
        ],
        "productType": 27,
        "productTypeDesc": "订单宝-银行精选",
        "dealerId": 100018947,
        "userId": 100071797,
        "signerName": "张三",
        "signerMobile": "15839886688",
        "lowerReaches": null,
        "lowerReachesId": null,
        "upperReaches": null,
        "upperReachesId": null,
        "labelInfo": null,
        "orderSourceNum": null,
        "createInvoice": null,
        "isExtension": null,
        "extensionBatchNo": null,
        "applyLoanAmount": 17000000,
        "applyLoanAmountCNY": "170,000",
        "totalCheckAmount": null,
        "matAmount": null,
        "isModifyInfo": true,
        "memo": null,
        "closeSource": null,
        "source": 3,
        "canTestClose": false,
        "isShowBankButton": true,
        "isDoBankButton": true,
        "isExportButton": false,
        "receiptInfoDTOS": [
            {
                "receiptAmount": 17000000,
                "receiptMemo": "",
                "isPrivatePayment": 0,
                "accountId": 100000271,
                "accountName": "上海科技有限公司",
                "bankCardNo": "123456789123456",
                "bankId": 8,
                "bankName": "招商银行",
                "province": "浙江省",
                "city": "杭州市",
                "bankBranch": "招商银行股份有限公司杭州海创园小微企业专营支行",
                "bankReceiptUrl": null,
                "type": null,
                "advanceTime": null,
                "remark": ""
            }
        ],
        "orderFollowerId": null,
        "orderFollowerName": null
    },
    {
        "applicationId": "YH202411050864001962",
        "orderId": null,
        "applyDate": 1730778517000,
        "taskCode": [
            "logisticsCheckCar",
            "waitPayment"
        ],
        "taskCodeDesc": [
            "物流验车",
            "待支付费用"
        ],
        "orderStatusDesc": "未推送",
        "applicationStatus": 5,
        "applicationStatusDesc": "审核中",
        "regionId": null,
        "areaName": null,
        "dealName": "上海安趣盈科技有限公司",
        "providerId": 100011125,
        "providerName": "上海科技有限公司",
        "providerUserId": 100028666,
        "providerUserName": "张三",
        "providerUserPhone": "15839886688",
        "isMakeOrder": true,
        "isSurvey": "尽调已过期",
        "contractAmount": 17000000,
        "contractAmountCNY": "170,000",
        "loanAmount": null,
        "loanAmountCNY": null,
        "managerId": 405,
        "manager": "花花",
        "managerNick": "花花",
        "userName": "张三",
        "userMobile": "17816869350",
        "contactsName": "李四",
        "contactsPhone": "17816860000",
        "storeId": null,
        "wareHouseDetail": null,
        "transportInfo": null,
        "totalCar": 2,
        "carDetail": [
            {
                "modelName": "宝骏530 2021款 全球车周年纪念版 1.5T 手动舒适型 5座",
                "uniqueNum": 1,
                "carUniqueList": []
            },
            {
                "modelName": "奥迪A4L 2020款 35 TFSI 时尚动感型",
                "uniqueNum": 1,
                "carUniqueList": []
            }
        ],
        "productType": 27,
        "productTypeDesc": "订单宝-银行精选",
        "dealerId": 100018947,
        "userId": 100071797,
        "signerName": "张三",
        "signerMobile": "15839886688",
        "lowerReaches": null,
        "lowerReachesId": null,
        "upperReaches": null,
        "upperReachesId": null,
        "labelInfo": [
            {
                "id": 13568,
                "labelId": 368,
                "label": "6",
                "memo": null,
                "status": null,
                "isDeleted": 0,
                "userId": 405,
                "userName": null,
                "gmtCreate": 1727332150000,
                "isFunctional": 0,
                "dateStr": null,
                "labelType": 0
            }
        ],
        "orderSourceNum": null,
        "createInvoice": null,
        "isExtension": null,
        "extensionBatchNo": null,
        "applyLoanAmount": 17000000,
        "applyLoanAmountCNY": "170,000",
        "totalCheckAmount": null,
        "matAmount": null,
        "isModifyInfo": true,
        "memo": null,
        "closeSource": null,
        "source": 3,
        "canTestClose": false,
        "isShowBankButton": null,
        "isDoBankButton": null,
        "isExportButton": false,
        "receiptInfoDTOS": [
            {
                "receiptAmount": 17000000,
                "receiptMemo": "",
                "isPrivatePayment": 0,
                "accountId": 100000271,
                "accountName": "上海科技有限公司",
                "bankCardNo": "123456789123456",
                "bankId": 8,
                "bankName": "招商银行",
                "province": "浙江省",
                "city": "杭州市",
                "bankBranch": "招商银行股份有限公司杭州海创园小微企业专营支行",
                "bankReceiptUrl": null,
                "type": null,
                "advanceTime": null,
                "remark": ""
            }
        ],
        "orderFollowerId": null,
        "orderFollowerName": null
    },
    {
        "applicationId": "YH202410220823277399",
        "orderId": null,
        "applyDate": 1729586904000,
        "taskCode": [
            "assessCarPrice"
        ],
        "taskCodeDesc": [
            "车辆核价"
        ],
        "orderStatusDesc": "未推送",
        "applicationStatus": 5,
        "applicationStatusDesc": "审核中",
        "regionId": null,
        "areaName": null,
        "dealName": "上海安趣盈科技有限公司",
        "providerId": 100011125,
        "providerName": "上海科技有限公司",
        "providerUserId": 100028666,
        "providerUserName": "张三",
        "providerUserPhone": "15839886688",
        "isMakeOrder": true,
        "isSurvey": "尽调已过期",
        "contractAmount": 38000000,
        "contractAmountCNY": "380,000",
        "loanAmount": null,
        "loanAmountCNY": null,
        "managerId": 471622995839938560,
        "manager": "张三",
        "managerNick": "张三",
        "userName": "张三",
        "userMobile": "17816869350",
        "contactsName": "李四",
        "contactsPhone": "17816860000",
        "storeId": null,
        "wareHouseDetail": null,
        "transportInfo": null,
        "totalCar": 4,
        "carDetail": [
            {
                "modelName": "奥迪A4L 2024款 40 TFSI 时尚动感型",
                "uniqueNum": 2,
                "carUniqueList": [
                    "VG0HDZPN5R2W48843",
                    "4ESC5LTH1AGS73407"
                ]
            },
            {
                "modelName": "宝骏530 2021款 全球车周年纪念版 1.5T 手动舒适型 5座",
                "uniqueNum": 2,
                "carUniqueList": [
                    "VWW3EUTP28LG04590",
                    "G494HW5K27PB83116"
                ]
            }
        ],
        "productType": 27,
        "productTypeDesc": "订单宝-银行精选",
        "dealerId": 100018947,
        "userId": 100071797,
        "signerName": "张三",
        "signerMobile": "15839886688",
        "lowerReaches": null,
        "lowerReachesId": null,
        "upperReaches": null,
        "upperReachesId": null,
        "labelInfo": null,
        "orderSourceNum": null,
        "createInvoice": null,
        "isExtension": null,
        "extensionBatchNo": null,
        "applyLoanAmount": 38000000,
        "applyLoanAmountCNY": "380,000",
        "totalCheckAmount": null,
        "matAmount": null,
        "isModifyInfo": true,
        "memo": null,
        "closeSource": null,
        "source": 0,
        "canTestClose": false,
        "isShowBankButton": true,
        "isDoBankButton": false,
        "isExportButton": false,
        "receiptInfoDTOS": [
            {
                "receiptAmount": 38000000,
                "receiptMemo": "",
                "isPrivatePayment": 0,
                "accountId": 100000271,
                "accountName": "上海科技有限公司",
                "bankCardNo": "123456789123456",
                "bankId": 8,
                "bankName": "招商银行",
                "province": "浙江省",
                "city": "杭州市",
                "bankBranch": "招商银行股份有限公司杭州海创园小微企业专营支行",
                "bankReceiptUrl": null,
                "type": null,
                "advanceTime": null,
                "remark": null
            }
        ],
        "orderFollowerId": null,
        "orderFollowerName": null
    },
    {
        "applicationId": "YH202410140460671474",
        "orderId": null,
        "applyDate": 1728887032000,
        "taskCode": [
            "logisticsCheckCar",
            "preAssessCarPrice"
        ],
        "taskCodeDesc": [
            "物流验车",
            "预核价"
        ],
        "orderStatusDesc": "未推送",
        "applicationStatus": 5,
        "applicationStatusDesc": "审核中",
        "regionId": null,
        "areaName": null,
        "dealName": "上海安趣盈科技有限公司",
        "providerId": 100011125,
        "providerName": "上海科技有限公司",
        "providerUserId": 100028666,
        "providerUserName": "张三",
        "providerUserPhone": "15839886688",
        "isMakeOrder": true,
        "isSurvey": "尽调已过期",
        "contractAmount": 20000000,
        "contractAmountCNY": "200,000",
        "loanAmount": null,
        "loanAmountCNY": null,
        "managerId": 405,
        "manager": "花花",
        "managerNick": "花花",
        "userName": "张三",
        "userMobile": "17816869350",
        "contactsName": "李四",
        "contactsPhone": "17816860000",
        "storeId": null,
        "wareHouseDetail": null,
        "transportInfo": null,
        "totalCar": 2,
        "carDetail": [
            {
                "modelName": "奥迪A4L 2020款 35 TFSI 时尚动感型",
                "uniqueNum": 2,
                "carUniqueList": []
            }
        ],
        "productType": 27,
        "productTypeDesc": "订单宝-银行精选",
        "dealerId": 100018947,
        "userId": 100071797,
        "signerName": "张三",
        "signerMobile": "15839886688",
        "lowerReaches": null,
        "lowerReachesId": null,
        "upperReaches": null,
        "upperReachesId": null,
        "labelInfo": [
            {
                "id": 13568,
                "labelId": 368,
                "label": "6",
                "memo": null,
                "status": null,
                "isDeleted": 0,
                "userId": 405,
                "userName": null,
                "gmtCreate": 1727332150000,
                "isFunctional": 0,
                "dateStr": null,
                "labelType": 0
            }
        ],
        "orderSourceNum": null,
        "createInvoice": null,
        "isExtension": null,
        "extensionBatchNo": null,
        "applyLoanAmount": 20000000,
        "applyLoanAmountCNY": "200,000",
        "totalCheckAmount": null,
        "matAmount": null,
        "isModifyInfo": true,
        "memo": null,
        "closeSource": null,
        "source": 3,
        "canTestClose": false,
        "isShowBankButton": null,
        "isDoBankButton": null,
        "isExportButton": false,
        "receiptInfoDTOS": [
            {
                "receiptAmount": 20000000,
                "receiptMemo": "",
                "isPrivatePayment": 0,
                "accountId": 100000271,
                "accountName": "上海科技有限公司",
                "bankCardNo": "123456789123456",
                "bankId": 8,
                "bankName": "招商银行",
                "province": "浙江省",
                "city": "杭州市",
                "bankBranch": "招商银行股份有限公司杭州海创园小微企业专营支行",
                "bankReceiptUrl": null,
                "type": null,
                "advanceTime": null,
                "remark": ""
            }
        ],
        "orderFollowerId": null,
        "orderFollowerName": null
    },
    {
        "applicationId": "YH202410140457921583",
        "orderId": null,
        "applyDate": 1728886317000,
        "taskCode": [
            "logisticsCheckCar",
            "preAssessCarPrice"
        ],
        "taskCodeDesc": [
            "物流验车",
            "预核价"
        ],
        "orderStatusDesc": "未推送",
        "applicationStatus": 5,
        "applicationStatusDesc": "审核中",
        "regionId": null,
        "areaName": null,
        "dealName": "上海安趣盈科技有限公司",
        "providerId": 100011125,
        "providerName": "上海科技有限公司",
        "providerUserId": 100028666,
        "providerUserName": "张三",
        "providerUserPhone": "15839886688",
        "isMakeOrder": true,
        "isSurvey": "尽调已过期",
        "contractAmount": 20000000,
        "contractAmountCNY": "200,000",
        "loanAmount": null,
        "loanAmountCNY": null,
        "managerId": 405,
        "manager": "花花",
        "managerNick": "花花",
        "userName": "张三",
        "userMobile": "17816869350",
        "contactsName": "李四",
        "contactsPhone": "17816860000",
        "storeId": null,
        "wareHouseDetail": null,
        "transportInfo": null,
        "totalCar": 2,
        "carDetail": [
            {
                "modelName": "奥迪A4L 2020款 35 TFSI 时尚动感型",
                "uniqueNum": 2,
                "carUniqueList": []
            }
        ],
        "productType": 27,
        "productTypeDesc": "订单宝-银行精选",
        "dealerId": 100018947,
        "userId": 100071797,
        "signerName": "张三",
        "signerMobile": "15839886688",
        "lowerReaches": null,
        "lowerReachesId": null,
        "upperReaches": null,
        "upperReachesId": null,
        "labelInfo": [
            {
                "id": 13568,
                "labelId": 368,
                "label": "6",
                "memo": null,
                "status": null,
                "isDeleted": 0,
                "userId": 405,
                "userName": null,
                "gmtCreate": 1727332150000,
                "isFunctional": 0,
                "dateStr": null,
                "labelType": 0
            }
        ],
        "orderSourceNum": null,
        "createInvoice": null,
        "isExtension": null,
        "extensionBatchNo": null,
        "applyLoanAmount": 20000000,
        "applyLoanAmountCNY": "200,000",
        "totalCheckAmount": null,
        "matAmount": null,
        "isModifyInfo": true,
        "memo": null,
        "closeSource": null,
        "source": 3,
        "canTestClose": false,
        "isShowBankButton": null,
        "isDoBankButton": null,
        "isExportButton": false,
        "receiptInfoDTOS": [
            {
                "receiptAmount": 20000000,
                "receiptMemo": "",
                "isPrivatePayment": 0,
                "accountId": 100000271,
                "accountName": "上海科技有限公司",
                "bankCardNo": "123456789123456",
                "bankId": 8,
                "bankName": "招商银行",
                "province": "浙江省",
                "city": "杭州市",
                "bankBranch": "招商银行股份有限公司杭州海创园小微企业专营支行",
                "bankReceiptUrl": null,
                "type": null,
                "advanceTime": null,
                "remark": ""
            }
        ],
        "orderFollowerId": null,
        "orderFollowerName": null
    },
    {
        "applicationId": "YH202410120815607758",
        "orderId": "CYH202410120001032331",
        "applyDate": 1728703539000,
        "taskCode": [
            "checkPartnerQualifications"
        ],
        "taskCodeDesc": [
            "运营初审"
        ],
        "orderStatusDesc": "未推送",
        "applicationStatus": 8,
        "applicationStatusDesc": "金融审核驳回",
        "regionId": null,
        "areaName": null,
        "dealName": "上海安趣盈科技有限公司",
        "providerId": 100011125,
        "providerName": "上海科技有限公司",
        "providerUserId": 100028666,
        "providerUserName": "张三",
        "providerUserPhone": "15839886688",
        "isMakeOrder": true,
        "isSurvey": "尽调已过期",
        "contractAmount": 21000000,
        "contractAmountCNY": "210,000",
        "loanAmount": null,
        "loanAmountCNY": "168,000",
        "managerId": 405,
        "manager": "花花",
        "managerNick": "花花",
        "userName": "张三",
        "userMobile": "17816869350",
        "contactsName": "李四",
        "contactsPhone": "17816860000",
        "storeId": null,
        "wareHouseDetail": null,
        "transportInfo": null,
        "totalCar": 2,
        "carDetail": [
            {
                "modelName": "奥迪A4L 2024款 40 TFSI 时尚动感型",
                "uniqueNum": 1,
                "carUniqueList": [
                    "62TNCDG755PR54270"
                ]
            },
            {
                "modelName": "宝骏530 2021款 全球车周年纪念版 1.5T 手动舒适型 5座",
                "uniqueNum": 1,
                "carUniqueList": [
                    "SKGMHUBV41P494926"
                ]
            }
        ],
        "productType": 27,
        "productTypeDesc": "订单宝-银行精选",
        "dealerId": 100018947,
        "userId": 100071797,
        "signerName": "张三",
        "signerMobile": "15839886688",
        "lowerReaches": null,
        "lowerReachesId": null,
        "upperReaches": null,
        "upperReachesId": null,
        "labelInfo": null,
        "orderSourceNum": null,
        "createInvoice": null,
        "isExtension": null,
        "extensionBatchNo": null,
        "applyLoanAmount": 21000000,
        "applyLoanAmountCNY": "210,000",
        "totalCheckAmount": null,
        "matAmount": null,
        "isModifyInfo": true,
        "memo": null,
        "closeSource": null,
        "source": 0,
        "canTestClose": false,
        "isShowBankButton": true,
        "isDoBankButton": true,
        "isExportButton": false,
        "receiptInfoDTOS": [
            {
                "receiptAmount": 21000000,
                "receiptMemo": "",
                "isPrivatePayment": 0,
                "accountId": 100000271,
                "accountName": "上海科技有限公司",
                "bankCardNo": "123456789123456",
                "bankId": 8,
                "bankName": "招商银行",
                "province": "浙江省",
                "city": "杭州市",
                "bankBranch": "招商银行股份有限公司杭州海创园小微企业专营支行",
                "bankReceiptUrl": null,
                "type": null,
                "advanceTime": null,
                "remark": null
            }
        ],
        "orderFollowerId": null,
        "orderFollowerName": null
    },
    {
        "applicationId": "YH202410120812598788",
        "orderId": null,
        "applyDate": 1728702573000,
        "taskCode": [
            "checkPartnerQualifications",
            "logisticsCheckCar",
            "preAssessCarPrice"
        ],
        "taskCodeDesc": [
            "运营初审",
            "物流验车",
            "预核价"
        ],
        "orderStatusDesc": "未推送",
        "applicationStatus": 5,
        "applicationStatusDesc": "审核中",
        "regionId": null,
        "areaName": null,
        "dealName": "上海安趣盈科技有限公司",
        "providerId": 100011125,
        "providerName": "上海科技有限公司",
        "providerUserId": 100028666,
        "providerUserName": "张三",
        "providerUserPhone": "15839886688",
        "isMakeOrder": true,
        "isSurvey": "尽调已过期",
        "contractAmount": 15000000,
        "contractAmountCNY": "150,000",
        "loanAmount": null,
        "loanAmountCNY": null,
        "managerId": 471622995839938560,
        "manager": "张三",
        "managerNick": "张三",
        "userName": "张三",
        "userMobile": "17816869350",
        "contactsName": "李四",
        "contactsPhone": "17816860000",
        "storeId": null,
        "wareHouseDetail": null,
        "transportInfo": null,
        "totalCar": 1,
        "carDetail": [
            {
                "modelName": "奥迪Q5 e-tron 2024款 50 e-tron quattro 光耀型 锦衣套装",
                "uniqueNum": 1,
                "carUniqueList": []
            }
        ],
        "productType": 27,
        "productTypeDesc": "订单宝-银行精选",
        "dealerId": 100018947,
        "userId": 100071797,
        "signerName": "张三",
        "signerMobile": "15839886688",
        "lowerReaches": null,
        "lowerReachesId": null,
        "upperReaches": null,
        "upperReachesId": null,
        "labelInfo": [
            {
                "id": 13568,
                "labelId": 368,
                "label": "6",
                "memo": null,
                "status": null,
                "isDeleted": 0,
                "userId": 405,
                "userName": null,
                "gmtCreate": 1727332150000,
                "isFunctional": 0,
                "dateStr": null,
                "labelType": 0
            }
        ],
        "orderSourceNum": null,
        "createInvoice": null,
        "isExtension": null,
        "extensionBatchNo": null,
        "applyLoanAmount": 15000000,
        "applyLoanAmountCNY": "150,000",
        "totalCheckAmount": null,
        "matAmount": null,
        "isModifyInfo": true,
        "memo": null,
        "closeSource": null,
        "source": 3,
        "canTestClose": false,
        "isShowBankButton": null,
        "isDoBankButton": null,
        "isExportButton": false,
        "receiptInfoDTOS": [
            {
                "receiptAmount": 15000000,
                "receiptMemo": "",
                "isPrivatePayment": 0,
                "accountId": 1254,
                "accountName": "上海科技有限公司",
                "bankCardNo": "123456789",
                "bankId": 8,
                "bankName": "招商银行",
                "province": "浙江省",
                "city": "杭州市",
                "bankBranch": "招商银行杭州分行城西支行",
                "bankReceiptUrl": null,
                "type": null,
                "advanceTime": null,
                "remark": ""
            }
        ],
        "orderFollowerId": null,
        "orderFollowerName": null
    },
    {
        "applicationId": "YH202410100772871114",
        "orderId": null,
        "applyDate": 1728545506000,
        "taskCode": [
            "logisticsCheckCar",
            "preAssessCarPrice"
        ],
        "taskCodeDesc": [
            "物流验车",
            "预核价"
        ],
        "orderStatusDesc": "未推送",
        "applicationStatus": 5,
        "applicationStatusDesc": "审核中",
        "regionId": null,
        "areaName": null,
        "dealName": "上海安趣盈科技有限公司",
        "providerId": 100011125,
        "providerName": "上海科技有限公司",
        "providerUserId": 100028666,
        "providerUserName": "张三",
        "providerUserPhone": "15839886688",
        "isMakeOrder": true,
        "isSurvey": "尽调已过期",
        "contractAmount": 25000000,
        "contractAmountCNY": "250,000",
        "loanAmount": null,
        "loanAmountCNY": null,
        "managerId": 405,
        "manager": "花花",
        "managerNick": "花花",
        "userName": "张三",
        "userMobile": "17816869350",
        "contactsName": "李四",
        "contactsPhone": "17816860000",
        "storeId": null,
        "wareHouseDetail": null,
        "transportInfo": null,
        "totalCar": 2,
        "carDetail": [
            {
                "modelName": "奥迪A4L 2024款 40 TFSI 时尚动感型",
                "uniqueNum": 1,
                "carUniqueList": [
                    "GRFSJJMX4ECEC9TF4"
                ]
            },
            {
                "modelName": "奥迪A4L 2024款 40 TFSI 时尚动感型",
                "uniqueNum": 1,
                "carUniqueList": [
                    "P0W7HHW583SZPE1W4"
                ]
            }
        ],
        "productType": 27,
        "productTypeDesc": "订单宝-银行精选",
        "dealerId": 100018947,
        "userId": 100071797,
        "signerName": "张三",
        "signerMobile": "15839886688",
        "lowerReaches": null,
        "lowerReachesId": null,
        "upperReaches": null,
        "upperReachesId": null,
        "labelInfo": [
            {
                "id": 13568,
                "labelId": 368,
                "label": "6",
                "memo": null,
                "status": null,
                "isDeleted": 0,
                "userId": 405,
                "userName": null,
                "gmtCreate": 1727332150000,
                "isFunctional": 0,
                "dateStr": null,
                "labelType": 0
            }
        ],
        "orderSourceNum": null,
        "createInvoice": null,
        "isExtension": null,
        "extensionBatchNo": null,
        "applyLoanAmount": 25000000,
        "applyLoanAmountCNY": "250,000",
        "totalCheckAmount": null,
        "matAmount": null,
        "isModifyInfo": true,
        "memo": null,
        "closeSource": null,
        "source": 3,
        "canTestClose": false,
        "isShowBankButton": true,
        "isDoBankButton": false,
        "isExportButton": false,
        "receiptInfoDTOS": [
            {
                "receiptAmount": 25000000,
                "receiptMemo": "",
                "isPrivatePayment": 0,
                "accountId": 100000271,
                "accountName": "上海科技有限公司",
                "bankCardNo": "123456789123456",
                "bankId": 8,
                "bankName": "招商银行",
                "province": "浙江省",
                "city": "杭州市",
                "bankBranch": "招商银行股份有限公司杭州海创园小微企业专营支行",
                "bankReceiptUrl": null,
                "type": null,
                "advanceTime": null,
                "remark": ""
            }
        ],
        "orderFollowerId": null,
        "orderFollowerName": null
    },
    {
        "applicationId": "YH202410100761101401",
        "orderId": null,
        "applyDate": 1728543373000,
        "taskCode": [
            "checkPartnerQualifications",
            "logisticsCheckCar",
            "preAssessCarPrice"
        ],
        "taskCodeDesc": [
            "运营初审",
            "物流验车",
            "预核价"
        ],
        "orderStatusDesc": "未推送",
        "applicationStatus": 5,
        "applicationStatusDesc": "审核中",
        "regionId": null,
        "areaName": null,
        "dealName": "上海安趣盈科技有限公司",
        "providerId": 100011125,
        "providerName": "上海科技有限公司",
        "providerUserId": 100028666,
        "providerUserName": "张三",
        "providerUserPhone": "15839886688",
        "isMakeOrder": true,
        "isSurvey": "尽调已过期",
        "contractAmount": 13000000,
        "contractAmountCNY": "130,000",
        "loanAmount": null,
        "loanAmountCNY": null,
        "managerId": 471622995839938560,
        "manager": "张三",
        "managerNick": "张三",
        "userName": "张三",
        "userMobile": "17816869350",
        "contactsName": "李四",
        "contactsPhone": "17816860000",
        "storeId": null,
        "wareHouseDetail": null,
        "transportInfo": null,
        "totalCar": 1,
        "carDetail": [
            {
                "modelName": "奥迪A7L 2024款 45 TFSI 豪华型",
                "uniqueNum": 1,
                "carUniqueList": []
            }
        ],
        "productType": 27,
        "productTypeDesc": "订单宝-银行精选",
        "dealerId": 100018947,
        "userId": 100071797,
        "signerName": "张三",
        "signerMobile": "15839886688",
        "lowerReaches": null,
        "lowerReachesId": null,
        "upperReaches": null,
        "upperReachesId": null,
        "labelInfo": null,
        "orderSourceNum": null,
        "createInvoice": null,
        "isExtension": null,
        "extensionBatchNo": null,
        "applyLoanAmount": 13000000,
        "applyLoanAmountCNY": "130,000",
        "totalCheckAmount": null,
        "matAmount": null,
        "isModifyInfo": true,
        "memo": null,
        "closeSource": null,
        "source": 0,
        "canTestClose": false,
        "isShowBankButton": true,
        "isDoBankButton": true,
        "isExportButton": false,
        "receiptInfoDTOS": [
            {
                "receiptAmount": 13000000,
                "receiptMemo": "",
                "isPrivatePayment": 0,
                "accountId": 100000271,
                "accountName": "上海科技有限公司",
                "bankCardNo": "123456789123456",
                "bankId": 8,
                "bankName": "招商银行",
                "province": "浙江省",
                "city": "杭州市",
                "bankBranch": "招商银行股份有限公司杭州海创园小微企业专营支行",
                "bankReceiptUrl": null,
                "type": null,
                "advanceTime": null,
                "remark": null
            }
        ],
        "orderFollowerId": null,
        "orderFollowerName": null
    },
    {
        "applicationId": "YH202410100750180326",
        "orderId": null,
        "applyDate": 1728529443000,
        "taskCode": [
            "checkPartnerQualifications",
            "logisticsCheckCar",
            "preAssessCarPrice"
        ],
        "taskCodeDesc": [
            "运营初审",
            "物流验车",
            "预核价"
        ],
        "orderStatusDesc": "未推送",
        "applicationStatus": 5,
        "applicationStatusDesc": "审核中",
        "regionId": null,
        "areaName": null,
        "dealName": "上海安趣盈科技有限公司",
        "providerId": 100011125,
        "providerName": "上海科技有限公司",
        "providerUserId": 100028666,
        "providerUserName": "张三",
        "providerUserPhone": "15839886688",
        "isMakeOrder": true,
        "isSurvey": "尽调已过期",
        "contractAmount": 17000000,
        "contractAmountCNY": "170,000",
        "loanAmount": null,
        "loanAmountCNY": null,
        "managerId": 471622995839938560,
        "manager": "张三",
        "managerNick": "张三",
        "userName": "张三",
        "userMobile": "17816869350",
        "contactsName": "李四",
        "contactsPhone": "17816860000",
        "storeId": null,
        "wareHouseDetail": null,
        "transportInfo": null,
        "totalCar": 2,
        "carDetail": [
            {
                "modelName": "奥迪A4L 2020款 35 TFSI 时尚动感型",
                "uniqueNum": 1,
                "carUniqueList": []
            },
            {
                "modelName": "宝骏530 2021款 全球车周年纪念版 1.5T 手动舒适型 5座",
                "uniqueNum": 1,
                "carUniqueList": []
            }
        ],
        "productType": 27,
        "productTypeDesc": "订单宝-银行精选",
        "dealerId": 100018947,
        "userId": 100071797,
        "signerName": "张三",
        "signerMobile": "15839886688",
        "lowerReaches": null,
        "lowerReachesId": null,
        "upperReaches": null,
        "upperReachesId": null,
        "labelInfo": null,
        "orderSourceNum": null,
        "createInvoice": null,
        "isExtension": null,
        "extensionBatchNo": null,
        "applyLoanAmount": 17000000,
        "applyLoanAmountCNY": "170,000",
        "totalCheckAmount": null,
        "matAmount": null,
        "isModifyInfo": true,
        "memo": null,
        "closeSource": null,
        "source": 3,
        "canTestClose": false,
        "isShowBankButton": true,
        "isDoBankButton": true,
        "isExportButton": false,
        "receiptInfoDTOS": [
            {
                "receiptAmount": 17000000,
                "receiptMemo": "",
                "isPrivatePayment": 0,
                "accountId": 100000271,
                "accountName": "上海科技有限公司",
                "bankCardNo": "123456789123456",
                "bankId": 8,
                "bankName": "招商银行",
                "province": "浙江省",
                "city": "杭州市",
                "bankBranch": "招商银行股份有限公司杭州海创园小微企业专营支行",
                "bankReceiptUrl": null,
                "type": null,
                "advanceTime": null,
                "remark": ""
            }
        ],
        "orderFollowerId": null,
        "orderFollowerName": null
    },
    {
        "applicationId": "YH202409300740529981",
        "orderId": null,
        "applyDate": 1727663389000,
        "taskCode": [
            "checkPartnerQualifications",
            "logisticsCheckCar",
            "preAssessCarPrice"
        ],
        "taskCodeDesc": [
            "运营初审",
            "物流验车",
            "预核价"
        ],
        "orderStatusDesc": "未推送",
        "applicationStatus": 5,
        "applicationStatusDesc": "审核中",
        "regionId": null,
        "areaName": null,
        "dealName": "上海安趣盈科技有限公司",
        "providerId": 100011125,
        "providerName": "上海科技有限公司",
        "providerUserId": 100028666,
        "providerUserName": "张三",
        "providerUserPhone": "15839886688",
        "isMakeOrder": true,
        "isSurvey": "尽调已过期",
        "contractAmount": 17000000,
        "contractAmountCNY": "170,000",
        "loanAmount": null,
        "loanAmountCNY": null,
        "managerId": 471622995839938560,
        "manager": "张三",
        "managerNick": "张三",
        "userName": "张三",
        "userMobile": "17816869350",
        "contactsName": "李四",
        "contactsPhone": "17816860000",
        "storeId": null,
        "wareHouseDetail": null,
        "transportInfo": null,
        "totalCar": 2,
        "carDetail": [
            {
                "modelName": "奥迪A4L 2020款 35 TFSI 时尚动感型",
                "uniqueNum": 1,
                "carUniqueList": []
            },
            {
                "modelName": "宝骏530 2021款 全球车周年纪念版 1.5T 手动舒适型 5座",
                "uniqueNum": 1,
                "carUniqueList": []
            }
        ],
        "productType": 27,
        "productTypeDesc": "订单宝-银行精选",
        "dealerId": 100018947,
        "userId": 100071797,
        "signerName": "张三",
        "signerMobile": "15839886688",
        "lowerReaches": null,
        "lowerReachesId": null,
        "upperReaches": null,
        "upperReachesId": null,
        "labelInfo": [
            {
                "id": 13568,
                "labelId": 368,
                "label": "6",
                "memo": null,
                "status": null,
                "isDeleted": 0,
                "userId": 405,
                "userName": null,
                "gmtCreate": 1727332150000,
                "isFunctional": 0,
                "dateStr": null,
                "labelType": 0
            }
        ],
        "orderSourceNum": null,
        "createInvoice": null,
        "isExtension": null,
        "extensionBatchNo": null,
        "applyLoanAmount": 17000000,
        "applyLoanAmountCNY": "170,000",
        "totalCheckAmount": null,
        "matAmount": null,
        "isModifyInfo": true,
        "memo": null,
        "closeSource": null,
        "source": 3,
        "canTestClose": false,
        "isShowBankButton": null,
        "isDoBankButton": null,
        "isExportButton": false,
        "receiptInfoDTOS": [
            {
                "receiptAmount": 17000000,
                "receiptMemo": "",
                "isPrivatePayment": 0,
                "accountId": 100000271,
                "accountName": "上海科技有限公司",
                "bankCardNo": "123456789123456",
                "bankId": 8,
                "bankName": "招商银行",
                "province": "浙江省",
                "city": "杭州市",
                "bankBranch": "招商银行股份有限公司杭州海创园小微企业专营支行",
                "bankReceiptUrl": null,
                "type": null,
                "advanceTime": null,
                "remark": ""
            }
        ],
        "orderFollowerId": null,
        "orderFollowerName": null
    }
]